application:
  actions: actions
  web: web-src

packages:
  starbucks:
    license: Apache-2.0
    actions:
      menu-provider:
        function: actions/menu-provider/index.js
        web: 'yes'
        runtime: nodejs:18
        annotations:
          require-adobe-auth: false
          final: true
        inputs:
          market: us
          LOG_LEVEL: info

      store-provider:
        function: actions/store-provider/index.js
        web: 'yes'
        runtime: nodejs:18
        annotations:
          require-adobe-auth: false
          final: true
        inputs:
          market: us
          LOG_LEVEL: info

      rewards-provider:
        function: actions/rewards-provider/index.js
        web: 'yes'
        runtime: nodejs:18
        annotations:
          require-adobe-auth: true
          final: true
        inputs:
          market: us
          LOG_LEVEL: info

      user-provider:
        function: actions/user-provider/index.js
        web: 'yes'
        runtime: nodejs:18
        annotations:
          require-adobe-auth: true
          final: true
        inputs:
          market: us
          LOG_LEVEL: info

      bff-proxy:
        function: actions/bff-proxy/index.js
        web: 'yes'
        runtime: nodejs:18
        annotations:
          require-adobe-auth: true
          final: true
        inputs:
          market: us
          LOG_LEVEL: info

      webhook:
        function: actions/webhook/index.js
        web: 'yes'
        runtime: nodejs:18
        annotations:
          require-adobe-auth: true
          final: true
        inputs:
          LOG_LEVEL: info
